# Generated by Django 6.0.1 on 2026-01-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenseitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
