# Generated by Django 6.0.1 on 2026-01-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_alter_expenseitem_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledger",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
